# Generated by Django 5.1.5 on 2025-01-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="Himanshu", max_length=100),
            preserve_default=False,
        ),
    ]
